---

- name: Input expectations are verified
  assert:
    that:
        - 'rhsm | default({}, True) | length or ansible_check_mode | default(False)'
        - 'rhsm.username | default("", True) | trim | length or ansible_check_mode | default(False)'
        - 'rhsm.password | default("", True) | trim | length or ansible_check_mode | default(False)'
        - 'role_path | is_dir'
        - 'unsubscribe | bool in [True, False]'
        - 'rhsm_retries | int >= 1'
        - 'rhsm_delay | int >= 0'

- name: System is registered and subscribed
  # Ansible-dependencies may not be installed yet!
  raw: '{{ lookup("template", role_path ~ "/templates/sub-man-cmd.j2") | trim }}'
  args:
    executable: "/bin/bash"  # Required to pass env. vars
  # Don't show credentials in the command-line
  environment:
    RHSM_USERNAME: "{{ rhsm.username }}"
    RHSM_PASSWORD: "{{ rhsm.password }}"
    RHSM_BASEURL: "{{ rhsm.baseurl | default('', True) }}"
    RHSM_SERVERURL: "{{ rhsm.serverurl | default('', True) }}"
    RHSM_ORG: "{{ rhsm.org | default('') }}"
  failed_when: result | failed and not result.stderr | search("already registered")
  register: result
  until: result | success
  retries: "{{ rhsm_retries }}"
  delay: "{{ rhsm_delay }}"
  when: rhsm | default('', True) | length and
        not ansible_check_mode | default(False)

- name: System is pinned to a specific release (no updates/installs past this version)
  raw: "subscription-manager release --set={{ rhsm.release }}"
  args:
    executable: "/bin/bash"
  when: not rhsm.release | default("", True) | trim | length

- name: System is unsubscribed and de-registered
  include_tasks: unsubscribe.yml
  when: unsubscribe | bool
