---

- name: Input expectations are verified
  assert:
    that:
        - 'unsubscribe | bool in [True, False]'

- name: System is unsubscribed, ignoring all errors and failures
  # Ansible-dependencies may not be installed yet!
  raw: "subscription-manager unregister"
  executable: "/bin/bash"
  ignore_errors: True
  failed_when: False  # Don't show red when unsubscribing an unsubscribed system
  register: result
  when: not ansible_check_mode | default(False) and
        unsubscribe | bool

- name: A failed raw operation is debugged
  debug:
    var: result
  when: result | failed
